- name: Create or Update CloudFormation Stack
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - include_vars: 'group_vars/{{ env }}.yml'

  roles:
    - role: network
      template_parameters:
        VpcName: '{{ project_name }}-VPC'

    - role: application
      template_parameters:
        BucketName: '{{ project_name }}-example-bucket'
