Description: "Creates the application resources"

Parameters:
  BucketName:
    Description: Example bucket name
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    BucketName:
      Ref: BucketName

Outputs:
  S3Bucket:
    Description: The example S3 bucket
    Value: !Ref S3Bucket
